CREATE TABLE Usuario(
	Id INT NOT NULL,
    CPF VARCHAR(255) NOT NULL,
    RG VARCHAR(255) NOT NULL,
    Nome VARCHAR(255) NOT NULL,
    NomeSocial VARCHAR(255),
    Telefone VARCHAR(255),
    Endereço VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Senha VARCHAR(255) NOT NULL,
    DataNascimento DATE,
    Genero CHAR(1),
    Naturalidade VARCHAR(255),
    PRIMARY KEY(Id),

    CONSTRAINT chk_gender_user
    	CHECK(Genero in ('M', 'F'))
);

CREATE TABLE Aluno(
    Matricula VARCHAR(255) NOT NULL,
    NomePai VARCHAR(255),
    NomeMae VARCHAR(255),
    InstituiçãoConclusaoEscolaridade VARCHAR(255) NOT NULL,
    AnoConclusaoEscolaridade INT NOT NULL,
    UsuarioId INT NOT NULL CONSTRAINT fk_usuario_aluno REFERENCES Usuario(Id),
    
    PRIMARY KEY(Matricula)
);

CREATE TABLE Professor(
    Identificacao VARCHAR(255) NOT NULL,
    Formacao VARCHAR(255) NOT NULL,
    Departamento VARCHAR(255) NOT NULL,
    UsuarioId INT NOT NULL CONSTRAINT fk_usuario_professor REFERENCES Usuario(Id),

    PRIMARY KEY(Identificacao)
);

CREATE TABLE Curso(
    Codigo INT NOT NULL,
    MatrizCurricular VARCHAR(10000) NOT NULL,
    DuracaoEmSemestre INT NOT NULL,
    CargaHoraria FLOAT NOT NULL,

    PRIMARY KEY(Codigo)
);

CREATE TABLE AlunoCurso(
    MatriculaALuno VARCHAR(255) NOT NULL CONSTRAINT fk_matricula_alunocurso REFERENCES Aluno(Matricula),
    CodigoCurso INT NOT NULL CONSTRAINT fk_codigo_alunocurso REFERENCES Curso(Codigo)
);

CREATE TABLE Disciplina(
    Id INT NOT NULL,
    Nome VARCHAR(255) NOT NULL,
    Horario TIMESTAMP NOT NULL,
    Periodo INT NOT NULL,
    Local VARCHAR(255) NOT NULL,
    IdentificacaoProfessor VARCHAR(255) NOT NULL CONSTRAINT fk_identificacaoProfessor_disciplina REFERENCES Professor(Identificacao),

    PRIMARY KEY(Id)
);

CREATE TABLE Conteudo(
	Id INT NOT NULL,
    Titulo VARCHAR(255) NOT NULL,
    Descricao VARCHAR(4000) NOT NULL,
    DisciplinaId INT NOT NULL CONSTRAINT fk_disciplina_conteudo REFERENCES Disciplina(Id),

    PRIMARY KEY(Id)
);

CREATE TABLE SHIPPERS
(
    SHIPPER_ID NUMBER(9) NOT NULL,
    COMPANY_NAME VARCHAR2(40 BYTE) NOT NULL,
    PHONE VARCHAR2(24 BYTE),
    CONSTRAINT PK_SHIPPERS PRIMARY KEY (SHIPPER_ID)
)

CREATE TABLE PRODUCTS
(
    PRODUCT_ID NUMBER(9) NOT NULL,
    PRODUCT_NAME VARCHAR2(40 BYTE) NOT NULL,
    SUPPLIER_ID NUMBER(9) NOT NULL,
    CATEGORY_ID NUMBER(9) NOT NULL,
    QUANTITY_PER_UNIT VARCHAR2(20 BYTE),
    UNIT_PRICE NUMBER(10,2) DEFAULT 0 NOT NULL 
    	CONSTRAINT CK_PRODUCTS_UNIT_PRICE CHECK (Unit_Price>=0),
    UNITS_IN_STOCK NUMBER(9) DEFAULT 0 NOT NULL 
    	CONSTRAINT CK_PRODUCTS_UNITS_IN_STOCK CHECK (Units_In_Stock>=0),
    UNITS_ON_ORDER NUMBER(9) DEFAULT 0 NOT NULL 
    	CONSTRAINT CK_PRODUCTS_UNITS_ON_ORDER CHECK (Units_On_Order>=0),
    REORDER_LEVEL NUMBER(9) DEFAULT 0 NOT NULL 
    	CONSTRAINT CK_PRODUCTS_REORDER_LEVEL CHECK (Reorder_Level>=0),
    DISCONTINUED CHAR(1 BYTE) DEFAULT 'N' NOT NULL 
    	CONSTRAINT CK_PRODUCTS_DISCONTINUED CHECK (Discontinued in ('Y','N')),
    CONSTRAINT PK_PRODUCTS PRIMARY KEY (PRODUCT_ID),
    CONSTRAINT FK_CATEGORY_ID FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID),
    CONSTRAINT FK_SUPPLIER_ID FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID)  
)
